# USER INPUT- BASIC CODING

1. Get input for variable name and age and print it.

Sample input:

John

25

Sample output:

"My name is: John"

"My age is: 25"

In [ ]:
name=input("Enter your name:")
age=int(input("Enter your age:"))
print("My name is:", name)
print("My age is:", age)

Enter your name:John
Enter your age:23
My name is: John
My age is: 23

2. Get input for variable name, age, address and print it.

Sample input:

John

25

Chennai

Sample output:

"My name is: John"

"My age is: 25"

"My address is: Chennai"

In [ ]:
name=input("Enter your name:")
age=int(input("Enter your age:"))
address=input('Enter your address:')
print("My name is:", name)
print("My age is:", age)
print("My address is:", address)

Enter your name:John
Enter your age:25
Enter your address:Chennai
My name is: John
My age is: 25
My address is: Chennai

3. Get integer input for variable a,b,c.

*   Multiply all the 3 variables (axbxc)
*   Add all 3 varaible (a+b+c)
*   Divide the multiplied value by added value. Print it.

Sample input:

2

3

4

Sample output:

2.6 (how expression works: 24/9 = 2.6)

In [ ]:
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
c=int(input("Enter a number:"))
Output=(a*b*c)/(a+b+c)
print(Output)

Enter a number:2
Enter a number:3
Enter a number:4
2.6666666666666665

4. Get input for variable name, score, department.
*   Get score for 100
*   Divide 100/10

Sample input:

Dhivya

97

CSE

Sample output:

"My name is Dhivya"

"My score is 9.7/10"

"My department is CSE"

In [ ]:
name=input("Enter your name:")
score=int(input("Enter your score:"))
department=input('Enter your department:')
print("My name is:", name)
print("My score is:", score/10,"/10")
print("My department is:", department)

Enter your name:Dhivya
Enter your score:97
Enter your department:CSE
My name is: Dhivya
My score is: 9.7 /10
My department is: CSE

# IF CONDITIONS

5. Get input for variable Mark.

If mark is greater than 35- print pass; Else- print fail.

Sample input:

Mark: 30

Sample output:

"Fail"

In [ ]:
Mark=int(input('Enter your mark'))
if (Mark>35):
  print("Pass")
else:
    print('Fail')

Enter your mark30
Fail

6. Get input for variable Income.

If Income is greater than 7000- print Not eligible for loan; Else- print eligible for loan.

Sample input:

Income: 7200

Sample output:

"Not eligible for loan"

In [ ]:
Income=int(input('enter your income:'))
if (Income>7000):
  print('not eligible for loan')
else:
  print("eligible for loan")

enter your income:7200
not eligible for loan

7. Get input for a number and check whether it is divisible by both 3 and 5 or not.

If yes then print, the number is divisible by 3 and 5. Else print the number is not divisible by 3 and 5.

In [ ]:
no=int(input('enter your no:"'))
if(no%3==0 and no%5==0):
  print('the no is divisible by 3&5')
else:
  print('the no is not divisible by 3&5')

enter your no:"35
the no is not divisible by 3&5

8. Get input for a number and find it is even or odd.

In [ ]:
no=int(input('Enter your number:'))
if(no%2==0):
  print("even no", no)
else:
  print("Odd no", no)

Enter your number:43
Odd no 43

9. Get Input for score out of 100.

If score is lesser than 35= 'Poor student'

If score is greater than 35 and lesser than 70= 'Average student'

If score is greater than 70= 'Good student'

In [ ]:
score=int(input('enter your score:'))
if(score<=35):
  print('poor student')
elif(score>35 and score<70):
  print('average student')
elif(score>70):
  print('Good student')
else:
  print('invalid student')

enter your score:79
Good student

10. Make a mini calculator. Get input for 2 numbers a and b.

Get input from user whether to add/sub/mul/div. If user selects add then add those two numbers and print result.

In [ ]:
a=int(input('enter no:'))
b=int(input('enter no:'))
operation=input('select operation, add/sub/mul/div')
if(operation=='add'):
  print(a+b)
elif(operation=='sub'):
  print(a-b)
elif(operation=='mul'):
  print(a*b)
elif(operation=='div'):
  print(a%b)
else:
  print('invalid number')

enter no:25
enter no:10
select operation, add/sub/mul/divdiv
5

11. Get an input for score- 70%

Only if the percentage is greater than 70, get input for his name, department, location. Then print you are eligible. If not print not eligible.

In [ ]:
score=int(input('enter your score:'))
if(score>=70):
  name=input('enter your name:')
  dept=input('enter your department:')
  location=input('enter your location:')
  print("You are eligible")
else:
  print('not eligible')

enter your score:55
not eligible

12. Get input for five subject marks. Find average mark.

If the average mark is less than 35- print 'Coaching class students'; else 'you are good to go'

In [ ]:
Tamil=int(input('enter your tamil mark:'))
English=int(input('enter your English mark:'))
Maths=int(input('enter your maths mark:'))
Science=int(input('enter your science mark:'))
Social=int(input('enter your social mark:'))
Average=((Tamil+English+Maths+Science+Social)/5)
print(Average)
if (Average<=35):
  print('coaching class student')
else:
  print('you are good to go')

enter your tamil mark:25
enter your English mark:20
enter your maths mark:30
enter your science mark:40
enter your social mark:10
25.0
coaching class student

13. Modify the code so that it prints a specific message when num is divisible by both 2 and 3.

Note: Don't use logical operators. Make use of nested if.

In [ ]:
num=int(input('enter a no:'))
if(num%2==0):
  if(num%3==0):
    print('divisible by both 2 & 3')
  else:
    print('num is divisible by 2 but  not divisible by 3')
else:
  print('num is not divisible by 2')

enter a no:56
num is divisible by 2 but  not divisible by & 3

# FOR LOOP:

14. Get input for number a and b and print the numbers between them.

Sample input:

2

6

Sample output:

3 4 5

In [ ]:
a=int(input('enter a num1:'))
b=int(input('enter a num2:'))
for i in range (a+1,b):
  print(i)

enter a num1:2
enter a num2:6
3
4
5

15. Print even numbers between 1 to 10

Sample ouput:
2,4,6,8,10

In [ ]:
for i in range(1,6):
  print(i*2)

2
4
6
8
10

16. Count the no of odd numbers between 1 to 10

sample output: 5

In [ ]:
count=0
for i in range(1,11):
  if(i%2!=0):
    count=count+1
print(count)

5


17. Count the no of odd and even numbers between 1 to 10

sample output: odd- 5

even-5

In [ ]:
even=0
odd=0
for i in range (1,11):
  if(i%2==0):
    even=even+1
  else:
    odd=odd+1
print("Even",even)
print("odd",odd)

Even 5
odd 5

**18**. Count the nos which are divisible by 3 and 5. Give range 1 to 100

In [ ]:
count=0
for i in range(1,100):
  if(i%3==0 and i%5==0):
    count=count+1
print(count)

6

19. Write a program to compute the sum of first 5 natural numbers and whole numbers

In [ ]:
sum=0
for i in range(1,6):
  sum=sum+i
print('sum of natural no',sum)

sum of natural no 15

In [ ]:
sum1=0
for i in range(5):
  sum1=sum1+i
print('sum of whole no',sum1)

sum of whole no 10

20. Write a program to read 10 numbers as user input and find their sum and average. (also try using list)

In [ ]:
sum=0
count=0
for i in range(10):
  n=int(input('enter a no:'))
  sum=sum+n
  count=count+i
print("sum",sum)
print("average", sum/count)

enter a no:10
enter a no:20
enter a no:10
enter a no:20
enter a no:10
enter a no:20
enter a no:10
enter a no:20
enter a no:10
enter a no:20
sum 150
average 3.3333333333333335

21. Print cube a number(get as user input)

sample output: Number is: 3 and cube of the 3 is: 9

In [ ]:
num=int(input('enter a num'))
cube=1
for i in range (3):
  cube=cube*num
print('num is:', num, 'cube is:', cube)

enter a num5
num is: 5 cube is: 125

# Nested loops:

In [ ]:
for i in range(1,5):
  print(str(i)+ 'day','apple given')
  for j in range(1,3):
    print(j,'basket given')

1day apple given
1 basket given
2 basket given
2day apple given
1 basket given
2 basket given
3day apple given
1 basket given
2 basket given
4day apple given
1 basket given
2 basket given

In [ ]:
for i in range(1,5):
  print('Week'+str(i))
  for j in range (1,8):
    print('Day' + str(j))

Week1
Day1
Day2
Day3
Day4
Day5
Day6
Day7
Week2
Day1
Day2
Day3
Day4
Day5
Day6
Day7
Week3
Day1
Day2
Day3
Day4
Day5
Day6
Day7
Week4
Day1
Day2
Day3
Day4
Day5
Day6
Day7

In [ ]:
for i in range(4):
  print('*',end='')

****

In [ ]:
for i in range (1,4):
  for j in range(i):
    print(i,end='')

122333

22. Print the below pattern

0

01

012

0123

In [ ]:
rows=3
for i in range (0,rows+1):
  for j in range(0,i+1):
    print(j,end='')
  print('')

0
01
012
0123

23. Print the below pattern


![Screenshot (42).png]()

In [ ]:
for i in range (6):
  for j in range(i):
    print('*',end='')
  print('')

*
**
***
****
*****

24. Print the below pattern

1

1 2

1 2 3

1 2 3 4

1 2 3 4 5

In [ ]:
rows=5
for i in range (1,rows+1):
  for j in range (1,i+1):
    print(j,end='')
  print('')

1
12
123
1234
12345

25. Print the below pattern

1

22

333

4444

55555

In [ ]:
for i in range (6):
  for j in range (i):
    print(i,end='')
  print('')

1
22
333
4444
55555

26. Print the below pattern

5 5 5 5 5

5 5 5 5

5 5 5

5 5

5

In [ ]:
n=int(input('enter a number:'))
for i in range(n,0,-1):
  for j in range(i):
    print(5,end='')
  print('')

enter a number:5
55555
5555
555
55
5

# While loops

27. Print a number from 1 to 5

In [ ]:
i=1
while(i<=5):
  print(i)
  i=i+1

1
2
3
4
5

28. Write a loop statement to print the below series (increase by 10, include ',' between numbers)

10,20,30,40,50,...200

In [ ]:
i=10
while(i<=200):
  print(i)
  i=i+10

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200

29. Write a program to print first 10 natural numbers in reverse order

In [ ]:
i=10
while (i>0):
  print(i)
  i=i-1

10
9
8
7
6
5
4
3
2
1

30. Write a program to find the factorial of a number

In [ ]:
i=3
fact=1
while i > 0 :
  fact= fact*i
  i -=1
print(fact)

6

In [ ]:
i=5
fact=1
while i>0:
  fact*=i
  i-=1
print(fact)

120

In [ ]:
i=6
fact=1
while i>0:
  fact *=i
  i -=1
print(fact)

720

# Functions

31. Create a function called add(), sub(), mul(), div(). Get input for a and inside every functions and print its result.

In [ ]:
def add ():
  a=int(input('enter a no:'))
  b=int(input('enter a no:'))
  print('add', a+b)
add()

def sub ():
  a=int(input('enter a no:'))
  b=int(input('enter a no:'))
  print('sub', a-b)
sub()

def mul ():
  a=int(input('enter a no:'))
  b=int(input('enter a no:'))
  print('mul',a*b)
mul()

def div ():
  a=int(input('enter a no:'))
  b=int(input('enter a no:'))
  print('div',a/b)
div()

enter a no:3
enter a no:3
add 6
enter a no:19
enter a no:5
sub 14
enter a no:30
enter a no:2
mul 60
enter a no:45
enter a no:5
div 9.0

32. Get a integer number from users and pass it to the function findevenorodd(). It should print if the number is even or odd.

In [ ]:
def findevenorodd():
  num = int(input('enter a no:'))
  if (num%2==0):
    print('even no', num)
  else:
    print ('odd no', num)
findevenorodd()

enter a no:5
odd no 5

33. Get a integer mark from users and pass it to the function findpassorfail(). It should print if the mark is pass or fail(mark< 35).

In [ ]:
def findpassorfail():
  mark = int(input('enter your mark:'))
  if (mark>=35):
    print(' the mark is pass', mark)
  else:
    print ('the mark is fail', mark)
findpassorfail()

enter your mark:25
the mark is fail 25

34. Get input for a and b, pass it to the fucntion printrange(). It should print the numbers a to b.

In [ ]:
def printrange():
  a = int(input('enter a num:'))
  b=int(input('enter a num:'))
  for i in range (a,b):
    print(i)
printrange()

enter a num:5
enter a num:10
5
6
7
8
9

In [ ]:
def printrange(a,b):
  a=int(input("enter a number"))
  b=int(input("enter a number"))
  for i in range(a,b+1):
    print(i)
printrange(a,b)

NameError: name 'a' is not defined

35. Get input for a and b, pass it to the fucntion sum(a,b). It should print the sum.

In [ ]:
def sum():
  a=int(input('enter a num1:'))
  b=int(input('enter a num2:'))
  print(a+b)
sum()

enter a num1:10
enter a num2:20
30